#include "MyreKrig.h"

UseAntBegin
UseAnt(SunMyre)
UseAnt(Servant)
UseAnt(ElephAnt)

/* Standard *
#UseAnt(A5)
#UseAnt(AntAgonist)
#UseAnt(Antsy)
#UseAnt(BayiMayi)
#UseAnt(BeoMyre)
#UseAnt(BlackHole)
#UseAnt(Caesar)
#UseAnt(Cirkus)
#UseAnt(Dummy)
#UseAnt(FirkAnt)
#UseAnt(FishBone)
#UseAnt(FormAnt)
#UseAnt(GOA)
#UseAnt(Speedy)
#UseAnt(GridAnt)
#UseAnt(Hex)
#UseAnt(Humanist)
#UseAnt(IBM)
#UseAnt(infAnt)
#UseAnt(Inkal)
#UseAnt(Kakao)
#UseAnt(Legions)
#UseAnt(LightCore3)
#UseAnt(Militant)
#UseAnt(myresyre)
#UseAnt(NanoMyre)
#UseAnt(NewDesert)
#UseAnt(NFAnt)
#UseAnt(OAA)
#UseAnt(Panoleon)
#UseAnt(Punk)
#UseAnt(Rambo)
#UseAnt(Rommel)
#UseAnt(Skak)
#UseAnt(SkyNET)
#UseAnt(SleepyAnt)
#UseAnt(Smiley)
#UseAnt(SunMyre)
#UseAnt(borg)
#UseAnt(TheDoctor)
#UseAnt(Tirsdag)
#UseAnt(Triumfant)
#UseAnt(Zero)
*/

/* 1-byte *
#UseAnt(AntAgonist)
#UseAnt(BlackHole)
#UseAnt(Blitz)
#UseAnt(Cascade)
#UseAnt(Equalizer)
#UseAnt(FishBone)
#UseAnt(InformAnts)
#UseAnt(Null)
#UseAnt(Rambo)
#UseAnt(SkyNET)
#UseAnt(Square)
#UseAnt(Turbo)
*/

UseAntEnd
